packages:
  - .

allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - core-js
  - sharp
